### ISSUE TITLE
Documenting how to update the Speedify package

### ISSUE THREAD

**Issue by onnimonni** [TalalMash/Unofficial-Speedify-Installer-For-OpenWrt#1]
I tried to have a look at the [`run.sh` script](https://github.com/TalalMash/Unofficial-Speedify-Installer-For-OpenWrt/blob/master/packages/ipkbuild/speedifyunofficial/data/usr/lib/speedifyunofficial/run.sh#L162-L167) and it looks that you have thought about the updates to speedify as well.

Does the router itself call the `run.sh` with the `update` parameter at certain time or should the user do it?

I can update the readme about this if you let me know how it works.

**Comment by TalalMash** [comment]
It updates on device restart to avoid interruption, pretty much like Speedify on desktop.
There is also update button:
![image](https://github.com/TalalMash/Unofficial-Speedify-Installer-For-OpenWrt/assets/96490382/92e7365c-9439-424b-aa64-eb9cf77790e0)

**Comment by onnimonni** [comment]
Ah that sounds like a very sensible default 💪 Thank you so much for this 🙇 

Can I buy you coffee or beer remotely?
Anything else I can do to help you out?

**Comment by TalalMash** [comment]
Thanks a lot for your offer, I'm not accepting donations at the moment, let me know if you encounter any issue. 😄
